#! /bin/bash

for FRUIT in orange apple
do
    echo $FRUIT
done

FRUITS="orange apple banana"
for FRUIT in $FRUITS
do
    echo $FRUIT
done

for var in 1 2 3
do
    echo $var
done

for var in {1..10}
do
    echo $var
done

for var in `seq 1 10`
do
    echo $var
done

for var in $(seq 1 10)
do
    echo $var
done

