#! /bin/bash

echo 'SHELL:' $SHELL
echo 'BASH:' $BASH
echo 'BASH_VERSION' $BASH_VERSION
echo 'CDPATH:' $CDPATH
echo 'EUID:' $EUID

test_func()
{
	echo 'FUNCNAME:' $FUNCNAME
}

test_func

echo 'HISTCMD' $HISTCMD
echo 'HISTFILE' $HISTFILE
echo 'HISTFILESIZE' $HISTFILESIZE
echo 'HISTSIZE' $HISTSIZE
echo 'HOSTNAME' $HOSTNAME
echo 'HOSTTYPE' $HOSTTYPE
echo 'MACHTYPE' $MACHTYPE
echo 'LANG' $LANG 
echo 'PWD' $PWD
echo 'OLDPWD' $OLDPWD
echo 'PATH' $PATH
echo 'PS1' $PS1
