#! /bin/bash

SCORE=95

case "$SCORE" in 
95) echo '95';;
94) echo '94';;
*)  echo 'Not match';;
esac

case "$SCORE" in 
    *[[:upper:]]*) echo 'Upper';;
    *[[:lower:]]*) echo 'Lower';;
    *[[:digit:]]*) echo 'Digit';;
    *) echo '*';;
esac

